# Base image
FROM ubuntu:22.04

# Define arguments
ARG JDBC_DATABASE
ARG JDBC_DATABASE_URL2
ARG JDBC_USERNAME
ARG JDBC_PASSWORD
ARG APP_TOKEN_ISSUER
ARG APP_SECRET_KEY
ARG MOTOR_API_URL
ARG MOTOR_API_KEY

# Set environment variables
ENV JDBC_DATABASE $JDBC_DATABASE
ENV JDBC_DATABASE_URL2 $JDBC_DATABASE_URL2
ENV JDBC_USERNAME $JDBC_USERNAME
ENV JDBC_PASSWORD $JDBC_PASSWORD
ENV APP_TOKEN_ISSUER $APP_TOKEN_ISSUER
ENV APP_SECRET_KEY $APP_SECRET_KEY
ENV MOTOR_API_URL $MOTOR_API_URL
ENV MOTOR_API_KEY $MOTOR_API_KEY

# Install OpenJDK 17 slim
RUN apt-get update && \
    apt-get install -y openjdk-17-jdk-headless && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY . .

RUN chmod +x mvnw
RUN ./mvnw package

EXPOSE 8081

CMD ["sh", "-c", "java -jar target/car-0.0.1-SNAPSHOT.jar"]
